# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d32c9857262ca19d38c1a36511905f26da456913958eb5b798679ae2d9afd7af564888e66be6d86c6ccde88126112f88f49ac8374a5094d47a351c1e9f45042b

test:
  secret_key_base: 1c583cd721f299c259478809203274055f82c8bc42748be9b9f541007a2e49e5f0dd3fe6728ae768a4f1f54752cdddca28c24cbc1752f26b4542b2ac35a87c80

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
